server:
  context-path: /shopecb2b2c
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8087
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: pro
  devtools:
    restart:
      enabled: true 
      additional-paths: src/main/java
      exclude: WEB-INF/**
  messages:
      fallbackToSystemLocale: false
  http:
    encoding:
      charset: UTF-8
      enabled: true 
      force: true 
  mobile:
    devicedelegatingviewresolver:
      enabled: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      #cluster-nodes: 172.18.26.18:9300
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enable: true
# 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#mybatis
mybatis-plus: 
  mapper-locations: mapper/*Dao.xml
  typeAliasesPackage: net.shopec.entity
  typeEnumsPackage: net.shopec.entity
  global-config: 
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId） 
    map-underscore-to-camel-case: true
    cache-enabled: false
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    # 公共字段自动填充
    metaObjectHandler: net.shopec.config.MyMetaObjectHandler
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    lazyLoadTriggerMethods: ""
    multipleResultSetsEnabled: false
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
